openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /banks:
    get:
      # summary: Returns a list of users
      responses:
        '200':
          # description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    bname:
                      type: string
                    balance:
                      type: integer